Some errors fixed. More checks added

diff --git a/korus_meta/scripts/build_map b/korus_meta/scripts/build_map
--- a/korus_meta/scripts/build_map
+++ b/korus_meta/scripts/build_map
@@ -18,10 +18,10 @@ while [ "$1" != "" ]; do
   case $1 in
     -l | --laser )  LASER_M="build_laser_map:=true"
                     ;;
-    -s | --starg )  STARGZ_M="stargz_laser_map:=true"
+    -s | --starg )  STARG_M="build_stargz_map:=true"
                     ;;
     -m | --map )    shift
-                    MAP_NAME="map_name:=$1"
+                    MAP_NAME="$1"
                     ;;
     -k | --korus )  shift
                     KORUS_ID=$1
@@ -50,17 +50,37 @@ else
   echo "Korus id: ${KORUS_ID}"
 fi
 
-# check MAP_NAME; it isn't mandatory; if it's not provided, we don't create a stargazer map
-if [ -z "$MAP_NAME" ] && [ -n "$STARGZ_M" ]; then
+if [ -z "$MAP_NAME" ] && [ -n "$STARG_M" ]; then
   echo "Map name required when creating a stargazer map"
   usage
   exit
 fi
 
-if [ -z "$LASER_M" ] && [ -z "$STARGZ_M" ]; then
+if [ -n "$MAP_NAME" ] && [ -z "$LASER_M" ]; then
+  if [ -f "$MAP_NAME.yaml" ]; then
+    echo "Using map $MAP_NAME for localization. Stargazer landmarks will be relative to the origin of this map"
+  else
+    echo "ERROR: $MAP_NAME.yaml not found. Valid map required when creating a stargazer map"
+    exit 1
+  fi
+fi
+
+if [ -z "$LASER_M" ] && [ -z "$STARG_M" ]; then
   echo "You must build at least one map type"
   usage
   exit
 fi
 
-roslaunch korus_meta build_map_standalone.launch $LASER_M $STARGZ_M $MAP_NAME --screen
+# Set to false the maps not desired, so we are immune to positive default values
+if [ -z "$LASER_M" ]; then
+  LASER_M="build_laser_map:=false"
+fi
+if [ -z "$STARG_M" ]; then
+  LASER_M="build_stargz_map:=false"
+fi
+
+if [ -n "$MAP_NAME" ]; then
+  MAP_NAME="map_name:=$MAP_NAME"
+fi
+
+roslaunch korus_meta build_map_standalone.launch $LASER_M $STARG_M $MAP_NAME --screen
